---
title: "Cards Againt Humanity"
author: "Judith"
date: "13-04-2020"
output: html_document
---

# Reading in data
```{r setup}
library(tidyverse)
library(ggplot2)

game1 <- read_csv2("Cards_Against_Humanity_1_anonymised.csv") %>% mutate(Game = "Game 1")
game2 <- read_csv2("Cards_Against_Humanity_2_anonymised.csv") %>% mutate(Game = "Game 2")

games <- rbind(game1, game2)
```

# Descriptives
```{r descriptives}
#Number of wins per player
game1 %>% group_by(Winner) %>% summarise(wins = n()) %>% arrange(desc(wins))

#Number of wins given to another person
game1 %>% group_by(Judge, Winner) %>% summarise(points = n()) ##these are guesses as we are not fully sure about the placement of the wins
```

# Plot
```{r plot}
games %>% 
  select(-Notes) %>% 
  drop_na() %>% 
  ggplot(aes(x = Round, y = Winner, col = Judge)) +
  geom_point(cex = 3) +
  facet_wrap(~ Game, nrow = 2) +
  theme_minimal() +
  labs(title = "Winner of each round")
```

```{r}
ggsave("winners.png")
```

